version: '2'
services:

  # simple myself setup
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: luigipat
    volumes:
      - ./ressources/coursapple.sql:/docker-entrypoint-initdb.d/init.sql
     

  # grafana used for graphing mysql data
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '81:3000'
    #build:
      # cela fait référence au Dockerfile implicitement, nous aurions pu mettre ./ ou .
      #context: .
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
      GRAFANA_ADMIN_USER: admin
      GRAFANA_ADMIN_PASSWORD: admin
      GF_AUTH_ORG_ROLE: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/CoursApple.json
    volumes:
      - ./dashboards/:/etc/grafana/provisioning/dashboards/
      - ./datasources/:/etc/grafana/provisioning/datasources/

  