{
 "title": "apple",
 "time": { "from": "2020-03-19T23:00:00.000Z", "to": "2020-03-20T22:59:59.000Z" },
 "panels": [
  {
   "title": "Evolution du cours sur un an ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Close,\n  Low,\n  Hight,\n  Open\nFROM coursapple\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Volume actions apple sur 1 an",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Volume\nFROM coursapple\nORDER BY Date"
    }
   ]
  },
  {
   "title": "cours 20/03/2020",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Volume,\n  Open,\n  Hight,\n  Low,\n  Close\nFROM coursapple\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "cours 18/03/2021",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Volume,\n  Open,\n  Hight,\n  Low,\n  Close\n  \nFROM coursapple\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  }
 ]
}